[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-demo"
version = "0.4.0"
description = "NetBox plugin for demo instances (not for production use)"
readme = "README.md"
license = { file = "LICENSE.txt" }
